README.md

Add testing feature to README

---

.github/ISSUE_TEMPLATE/Event_Schema_Request.md
.github/ISSUE_TEMPLATE/Support.md

Add issue template for a new event schema request & support question.
Closes #16.

New issue templates for event schema request & support question

---

README.md

Fixes an issue pointing to the contract docs

Fix event contract link

---

docs/index.md

Provide decent title for docs home page

Provide decent title for docs home page

---

src/Arcus.EventGrid.Testing/Infrastructure/Hosts/ServiceBus/ServiceBusEventConsumerHost.cs
src/Arcus.EventGrid.Tests.Integration/appsettings.json

Remove hybrid connection legacy where we can already

Remove hybrid connection legacy where we can already

---

src/Arcus.EventGrid.Publishing/EventGridPublisher.cs
src/Arcus.EventGrid.Publishing/Interfaces/IEventGridPublisher.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventPublishingTests.cs
src/Arcus.EventGrid.Tests.Unit/Events/SerializationTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/EventGridParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/RawEventParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherTests.cs
src/Arcus.EventGrid/Contracts/RawEvent.cs
src/Arcus.EventGrid/Extensions/StringExtensions.cs

Provide capability to push raw events.
Closes #57

Provide capability to push raw events

---

src/Arcus.EventGrid.Publishing/EventGridPublisherBuilder.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherBuilderTests.cs

Make sure raw URIs are wellformed.
Relates to #67

Make sure raw URIs are wellformed

---

src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/HybridConnections/HybridConnectionHost.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/ServiceBus/ServiceBusEventConsumerHost.cs

Provide logging in case event id was not found to improve troubleshooting.

Provide logging in case event id was not found & case-insensitive event id lookup

---

docs/features/publishing-events.md
docs/features/running-integration-tests.md
src/Arcus.EventGrid.Publishing/EventGridPublisher.cs
src/Arcus.EventGrid.Publishing/Interfaces/IEventGridPublisher.cs
src/Arcus.EventGrid.Security/EventGridSubscriptionValidator.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/HybridConnections/HybridConnectionHost.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/ServiceBus/ServiceBusEventConsumerHost.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventPublishingTests.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherTests.cs

REFACTOR: suffix all async methods with '...Async'

---

docs/features/publishing-events.md

Documenting the `EventGridPublisher.PublishRaw` feature.
Closes #57

DOC: publishing raw events

---

src/Arcus.EventGrid.Publishing/EventGridPublisher.cs
src/Arcus.EventGrid.Publishing/Interfaces/IEventGridPublisher.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventPublishingTests.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherTests.cs

Add possibility to publish many raw events with the already defined
`RawEvent` type.
Closes #74

FEAT: add 'EventGridPublisher.PublishManyRawAsync'

---

docs/features/publishing-events.md

DOC: add '.PublishManyRawAsync' to documentation

---

src/Arcus.EventGrid.Testing/Infrastructure/Hosts/HybridConnections/HybridConnectionHost.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/ServiceBus/ServiceBusEventConsumerHost.cs

Suffix remaining methods with Async

---

build/ci-build.yml

Adds the CI build as a YAML build (without the Github Package Registr y for now).

FEAT: add YAML file for CI build

---

build/myget-release.yml

FEAT: add YAML release to MyGet

---

docs/features/create-custom-events.md

DOC: create custom events

---

docs/features/deserializing-events.md
docs/index.md

DOCS: add CloudEvent parsing support

---

docs/features/deserializing-events.md

Provide link to built-in Azure schemas

Docs - Provide link to built-in Azure schemas

---

docs/features/deserializing-events.md
src/Arcus.EventGrid.Tests.Integration/Publishing/EventPublishingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/EventParsingTests.cs
src/Arcus.EventGrid/EventBatch.cs
src/Arcus.EventGrid/Parsers/EventGridParser.cs

Renamed EventGridBatchEvent to EventBatch

---

src/Arcus.EventGrid/Arcus.EventGrid.csproj

CHORE: update CloudEvents package to v1.3.x

---

src/Arcus.EventGrid.Security/Arcus.EventGrid.Security.csproj
src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj

Relates to https://github.com/arcus-azure/arcus/issues/50

Chore - update EventGrid projects with netcore3.0 FrameworkReference

---

docs/features/publishing-events.md

Docs - provide raw event publishing feature docs

---

src/Arcus.EventGrid.Publishing/EventGridPublisher.cs
src/Arcus.EventGrid.Publishing/Interfaces/IEventGridPublisher.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/CloudEventPublishing.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridEventPublishingTests.cs

Feature - add event publishing overload with subject (w/out event time)

---

src/Arcus.EventGrid.Tests.Unit/Parsing/CloudEventParsingTests.cs
src/Arcus.EventGrid/Extensions/JObjectExtensions.cs
src/Arcus.EventGrid/Parsers/EventParser.cs

Test - add unit test to determine CloudEvent schema on events

---

src/Arcus.EventGrid.Tests.Integration/Fixture/EventGridTopicEndpoint.cs
src/Arcus.EventGrid.Tests.Integration/Fixture/TestConfig.cs
src/Arcus.EventGrid.Tests.Integration/appsettings.json

Azure DevOps variables have been cleaned up & added what is required.
Closes #127

Provide CloudEvent setup in Azure subscription

---

src/Arcus.EventGrid.Publishing/Arcus.EventGrid.Publishing.csproj
src/Arcus.EventGrid.Publishing/EventGridPublisher.cs
src/Arcus.EventGrid.Publishing/EventGridPublisherBuilderResult.cs
src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj

Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Follow-up for https://github.com/arcus-azure/arcus.security/pull/198 as they cannot run together atm, same issue in https://github.com/arcus-azure/arcus.eventgrid/pull/146

Migrate from Polly-Signed to Polly

---

src/Arcus.EventGrid.Security.Core/Extensions/IServiceCollectionExtensions.cs
src/Arcus.EventGrid.Security.Core/Validation/EventGridSubscriptionValidator.cs
src/Arcus.EventGrid.Security.WebApi/EventGridSubscriptionValidationActionFilter.cs

Fixes typo in EventGrid subscription validation.

chore: fix typo in security project

---

src/Arcus.EventGrid.Publishing/Arcus.EventGrid.Publishing.csproj
src/Arcus.EventGrid.Security.AzureFunctions/Arcus.EventGrid.Security.AzureFunctions.csproj
src/Arcus.EventGrid.Security.AzureFunctions/Extensions/IFunctionsHostBuilderExtensions.cs
src/Arcus.EventGrid.Security.Core/Arcus.EventGrid.Security.Core.csproj
src/Arcus.EventGrid.Security.WebApi/Arcus.EventGrid.Security.WebApi.csproj
src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridEventPublishingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/AzureIoTHubParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/AzureStorageParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/EventGridBlobParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/EventGridIoTHubParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/EventGridParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/EventParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Parsing/RawEventParsingTests.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherTests.cs
src/Arcus.EventGrid/Arcus.EventGrid.csproj
src/Arcus.EventGrid/Contracts/Interfaces/IEvent.cs
src/Arcus.EventGrid/Extensions/StringExtensions.cs

Treat warnings as errors in all production code projects.
Relates to https://github.com/arcus-azure/arcus/issues/196

chore: treat warnings as errors

---

src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/ServiceBus/ServiceBusEventConsumerHost.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/CloudEventPublishing.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridEventPublishingTests.cs

Fixes the invalid timeout functionality upon failed non-timeout failures.
Closes #195

test: fix cloud event filter timeout

---

src/Arcus.EventGrid.Publishing/Arcus.EventGrid.Publishing.csproj
src/Arcus.EventGrid.Security.AzureFunctions/Arcus.EventGrid.Security.AzureFunctions.csproj
src/Arcus.EventGrid.Security.Core/Arcus.EventGrid.Security.Core.csproj
src/Arcus.EventGrid.Security.WebApi/Arcus.EventGrid.Security.WebApi.csproj
src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj
src/Arcus.EventGrid/Arcus.EventGrid.csproj

Adds package readme project tag to project files.
Relates to https://github.com/arcus-azure/arcus/issues/209

chore: add package readme project tag

---

docs/preview/01-index.md

Adds introduction section to explain the general contents of the Arcus EventGrid library.

docs: add introduction section

---

docs/preview/02-Features/publishing-events.md
src/Arcus.EventGrid.Core/Publishing/EventGridPublisherClientWithTracking.cs
src/Arcus.EventGrid.Core/Publishing/Extensions/AzureClientFactoryBuilderExtensions.cs
src/Arcus.EventGrid.Tests.Integration/Fixture/EventGridTopicEndpoint.cs
src/Arcus.EventGrid.Tests.Integration/Fixture/MockServiceBusEventConsumerHost.cs
src/Arcus.EventGrid.Tests.Integration/Fixture/TemporaryManagedIdentityConnection.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridPublisherClientWithTrackingCloudEventsTests.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridPublisherClientWithTrackingEventGridEventTests.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridPublisherClientWithTrackingTests.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/Fixture/EventOptionsFixture.cs
src/Arcus.EventGrid.Tests.Integration/appsettings.json
src/Arcus.EventGrid.Tests.Unit/Publishing/AzureClientFactoryBuilderExtensionsTests.cs

Adds Azure Managed Identity authentication support to event publishing.
Closes #190

feat: add managed identity support to event publishing

---

src/Arcus.EventGrid.Core/Publishing/Extensions/AzureClientFactoryBuilderExtensions.cs

Fix the invalid operation exception messages thrown upon missing dependent Azure EventGrid publisher client services.
Closes #257

fix: exception messages dependent eventgrid publisher client services

---

docs/preview/02-Features/deserializing-events.md
docs/preview/02-Features/endpoint-validation.md
docs/preview/02-Features/running-integration-tests.md

Remove the table of contents in the preview feature documetation pages.

chore: remove table of contents

---

.github/workflows/code-coverage.yml
README.md
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
src/Arcus.EventGrid.Testing/Logging/ConsoleLogger.cs
src/Arcus.EventGrid.Testing/Logging/NoOpLogger.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridPublisherClientWithTrackingCloudEventsTests.cs
src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridPublisherClientWithTrackingEventGridEventTests.cs
src/Arcus.EventGrid.Tests.Unit/Arcus.EventGrid.Tests.Unit.csproj
src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherWithTrackingTests.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/Fixtures/InMemoryEventGridPublisherClient.cs
src/Arcus.EventGrid.Tests.Unit/Publishing/Fixtures/StubEventGridPublisherClientWithTracking.cs
src/Arcus.EventGrid.Tests.Unit/Security/EventGridAuthorizationFilterTests.cs
src/Arcus.EventGrid.Tests.Unit/Security/EventGridSubscriptionValidationActionFilterTests.cs
src/Arcus.EventGrid.Tests.Unit/Security/Extensions/FilterCollectionExtensionsTests.cs
src/Arcus.EventGrid.Tests.Unit/Testing/EventConsumerHostTests.cs
src/Arcus.EventGrid.Tests.Unit/Testing/Fixture/InMemoryEventConsumerHost.cs
src/Arcus.EventGrid.Tests.Unit/Testing/ServiceBusEventConsumerHostOptionsTests.cs
src/Arcus.EventGrid.Tests.Unit/Testing/ServiceBusEventConsumerHostTests.cs

Add code coverage reporting.
Relates to https://github.com/arcus-azure/arcus/issues/264

chore: add code coverage

---

.github/workflows/code-coverage.yml
.github/workflows/codeql-analysis.yml
build/ci-build.yml
build/nuget-release.yml
build/variables/build.yml
src/Arcus.EventGrid.Core/Arcus.EventGrid.Core.csproj
src/Arcus.EventGrid.Security.AzureFunctions/Arcus.EventGrid.Security.AzureFunctions.csproj
src/Arcus.EventGrid.Security.Core/Arcus.EventGrid.Security.Core.csproj
src/Arcus.EventGrid.Security.Core/Validation/EventGridSubscriptionValidator.cs
src/Arcus.EventGrid.Security.WebApi/Arcus.EventGrid.Security.WebApi.csproj
src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj
src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
src/Arcus.EventGrid.Tests.Core/Arcus.EventGrid.Tests.Core.csproj
src/Arcus.EventGrid.Tests.Integration/Arcus.EventGrid.Tests.Integration.csproj
src/Arcus.EventGrid.Tests.Unit/Arcus.EventGrid.Tests.Unit.csproj

Add .NET 8 preview support with previously preview-supported Arcus libraries Observability & Security.

chore: support net8.0 preview
