arcus-azure/arcus.eventgrid

- README.md
Configure "Deploy to Azure" button to make it easier to get started with running the tests.
> Configure "Deploy to Azure" button

- docs/features/publishing-events.md
The last code sample doesn't look nice, this makes it use a code block as the other code snippets on the page do.
> Align multiple events publishing

- src/Arcus.EventGrid.Publishing/EventGridPublisher.cs
- src/Arcus.EventGrid.Publishing/EventGridPublisherBuilder.cs
- src/Arcus.EventGrid.Publishing/EventGridPublisherBuilderResult.cs
- src/Arcus.EventGrid.Publishing/Interfaces/IEventGridPublisherBuilderWithAuthenticationKey.cs
- src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherBuilderTests.cs
- src/Arcus.EventGrid.Tests.Unit/Publishing/EventGridPublisherTests.cs
FEAT: add overload with Uri for EventGridPublisherBuilder  …
Because we could validate on the right kind of HTTP URL that's been
given, we could _Fail Fast_ without waiting till the actual publishing
of events fails and warn the user during the actual configuration of the
builder.
Closes #24
> FEAT: add overload with Uri for EventGridPublisherBuilder

- src/Arcus.EventGrid.All/Arcus.EventGrid.All.csproj
- src/Arcus.EventGrid.Azure/Arcus.EventGrid.Azure.csproj
- src/Arcus.EventGrid.EventHubs/Arcus.EventGrid.EventHubs.csproj
- src/Arcus.EventGrid.IoTHub/Arcus.EventGrid.IoTHub.csproj
- src/Arcus.EventGrid.Publishing/Arcus.EventGrid.Publishing.csproj
- src/Arcus.EventGrid.Security/Arcus.EventGrid.Security.csproj
- src/Arcus.EventGrid.Storage/Arcus.EventGrid.Storage.csproj
- src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj
- src/Arcus.EventGrid/Arcus.EventGrid.csproj
During the build of the NuGet packages, the XML docs weren't part of the
package. Meaning no docs during development.
This commit lets the projects generate such a documentation file
which will automatically be part of the also automatically generate NuGet package.
> DOC: add XML docs to nupkg

- docs/features/deserializing-events.md
- docs/features/endpoint-validation.md
- docs/features/running-integration-tests.md
Apperently some feature docs had a diff backwards arrow; leading to a broken page.
Fixed by removing the unnecessary trailing `/arcus.eventgrid`.
> DOC: fix broken backwards arrow

- docs/features/create-custom-events.md
- docs/features/deserializing-events.md
- docs/preview/features/create-custom-events.md
- docs/preview/features/deserializing-events.md
- docs/v2.0.0/features/deserializing-events.md
- docs/v2.1.0/features/deserializing-events.md
- docs/v2.2.0/features/deserializing-events.md
- docs/v2.3.0/features/deserializing-events.md
- docs/v2.4.0/features/deserializing-events.md
- docs/v3.0.0/features/create-custom-events.md
- docs/v3.0.0/features/deserializing-events.md
Add the missing `using` statements to the feature docs.
Relates to https://github.com/arcus-azure/arcus/issues/107
> Docs - add missing 'using's to the feature docs

- .github/semantic.yml
Adds Semantic config file so that it only validates the PR's title.
Relates to https://github.com/arcus-azure/arcus/issues/121
> fix: create Semantic config

- src/Arcus.EventGrid.Publishing/EventGridPublisherBuilderResult.cs
Apperently, this was still using the sync policy.
> fix: use correct NoOp async policy

- docs/preview/02-Features/running-integration-tests.md
- src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
- src/Arcus.EventGrid.Testing/Infrastructure/Hosts/ServiceBus/ServiceBusEventConsumerHost.cs
- src/Arcus.EventGrid.Tests.Core/ArcusAssert.cs
- src/Arcus.EventGrid.Tests.Integration/Publishing/CloudEventPublishing.cs
- src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridEventPublishingTests.cs
- src/Arcus.EventGrid/Contracts/Event.cs
Add custom event filters to the `EventConsumerHost` to have more approaches on receiving events.
Closes #178
> feat: add az event filters to test event consumer

- .github/ISSUE_TEMPLATE/Feature_request.md
Other repo's were using a different template. Let's use the same one here.
> fix: streamline issue template with other Arcus repo's

- src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
Be explicit when we receive no events, because otherwise and empty log statement is shown which implicitly shows there's no events.
> test: be explicit on receiving no events

- docs/preview/02-Features/endpoint-validation.md
- src/Arcus.EventGrid.Security/EventGridSubscriptionValidator.cs
- src/Arcus.EventGrid.Security/ResultWithChallenge.cs
Add remaining obsolete types and add deprecation message on the feature docs page.
Closes #204
> docs: deprecate old security project

- src/Arcus.EventGrid.Tests.Unit/Events/SerializationTests.cs
- src/Arcus.EventGrid.Tests.Unit/Parsing/EventParsingTests.cs
- src/Arcus.EventGrid/Contracts/Event.cs
- src/Arcus.EventGrid/Parsers/EventConverter.cs
Make sure that when serializing the `Event` directly, it makes sure that it serializes to the right event type.
Closes #200
> fix: general event serialization should take into acount cloud events and event grid events

- build/variables/build.yml
- src/Arcus.EventGrid.All/Arcus.EventGrid.All.csproj
- src/Arcus.EventGrid.Publishing/Arcus.EventGrid.Publishing.csproj
- src/Arcus.EventGrid.Security/Arcus.EventGrid.Security.csproj
- src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj
- src/Arcus.EventGrid.Tests.Core/Arcus.EventGrid.Tests.Core.csproj
- src/Arcus.EventGrid.Tests.InMemoryApi/Arcus.EventGrid.Tests.InMemoryApi.csproj
- src/Arcus.EventGrid.Tests.Integration/Arcus.EventGrid.Tests.Integration.csproj
- src/Arcus.EventGrid.Tests.Unit/Arcus.EventGrid.Tests.Unit.csproj
- src/Arcus.EventGrid.Tests.Unit/Artifacts/EventSamples.Designer.cs
- src/Arcus.EventGrid.WebApi.Security/Arcus.EventGrid.WebApi.Security.csproj
- src/Arcus.EventGrid/Arcus.EventGrid.csproj
Adds .NET 6 as target framework on the different available projects.
Relates to https://github.com/arcus-azure/arcus/issues/106
> chore: upgrade to .net6.0

- src/Arcus.EventGrid.Core/Arcus.EventGrid.Core.csproj
Add `netstandard2.1` support to the `Arcus.EventGrid.Core` package, as dependent background jobs are also supporting `netstandard2.1`.
> chore: support netstandard2.1 eventgrid core

- .github/workflows/codeql-analysis.yml
Updates the CodeQL workflow version to v2 as v1 will be deprecated on December 7th 2022.
> chore: update coddql to v2

- src/Arcus.EventGrid.Testing/Arcus.EventGrid.Testing.csproj
- src/Arcus.EventGrid.Testing/Infrastructure/Hosts/EventConsumerHost.cs
- src/Arcus.EventGrid.Tests.Core/Arcus.EventGrid.Tests.Core.csproj
- src/Arcus.EventGrid.Tests.Core/ArcusAssert.cs
- src/Arcus.EventGrid.Tests.Integration/Publishing/CloudEventPublishing.cs
- src/Arcus.EventGrid.Tests.Integration/Publishing/EventGridEventPublishingTests.cs
Use new Azure SDK for messaging to use Microsoft's `CloudEvent` and `EventGridEvent` models.
> feat: use new az sdk in testing

- docs/preview/02-Features/running-integration-tests.md
- docs/versioned_docs/version-v3.3.0/02-Features/running-integration-tests.md
Fix 'Deploy to Azure' button in feature documentation.
Closes #264
> chore: fix deploy to azure button

- build/ci-build.yml
Use the `main` branch in the CI build trigger.
Relates to https://github.com/arcus-azure/arcus/issues/169
> chore: update CI build trigger to `main` branch

- docs/preview/01-index.md
- docs/versioned_docs/version-v3.3.0/01-index.md
Correct introduction section in the feature documentation to not include our deprecated event parsing and event contracts.
Closes #282
> docs: correct introduction section
